### ISSUE TITLE
DisplayCustomNotificationMessage refuses to create a block

### ISSUE THREAD

**Issue by LennardF1989** [Ludonope/BFPortalUnleashed#11]
Consider the following code:
```
ui.DisplayCustomNotificationMessage(
    ui.Message("Players: {}", player.AllPlayers().length),
    enums.CustomMessages.MessageText1,
    -1
);
```

I trick it into adding something once, but after that, it never worked anymore. `Uncaught TypeError: Property name expected type of string but got null`

I expect to get this:
![image](https://user-images.githubusercontent.com/869973/143789470-299e1fa4-1ca4-4d46-b305-e337a8e4b63c.png)

**Comment by LennardF1989** [comment]
Ahhh, figured it out - it's the `-1`! This is a valid input as it will leave the message on screen indefinitely. If you pick 0 or higher it works fine.

**Comment by Ludonope** [comment]
Oh yeah I forgot to document that issue, you can use `0-1` for it as a workaround.
There is a problem with unary operator preprocessing at the moment.
