### ISSUE TITLE
conditions: [] should be optional

### ISSUE THREAD

**Issue by LennardF1989** [Ludonope/BFPortalUnleashed#2]
Currently you'll get the following error: 
```Uncaught TypeError: Cannot read properties of undefined (reading 'map')```

Should be pretty easy to remedy.

On top of this: A function could be simplified to not requiring a `RuleBody` structure if you do not need any conditions.

For example:
```
mod.onGameModeStarted("Started", () => ({
    conditions: [],
    actions: () => {
        gameplay.EnableDefaultScoring(false);
    }
}));
```

Could be simplified to:
```
mod.onGameModeStarted("Started", () => {
    gameplay.EnableDefaultScoring(false);
});
```

The preprocessor will just convert the simplified version back to the full version, before compiling happens.

**Comment by Ludonope** [comment]
Yeah not a bad idea, I think it's even doable without touching preprocessing at all, just by checking if it's an `Object` or `Function`
